config/routes.rb
Rails.application.routes.draw do

  resources :articles
root 'devices#home'

resources :brands do
get '/correct', to: 'brands#correct'
get '/count', to: 'brands#count_scrapes'
resources :devices
end

resources :devices do
resources :reviews
get '/compare', to: 'devices#compare'
end

get '/adminpanel', to: 'devices#adminpanel'

get '/popular', to: 'devices#popular'

devise_for :users, :controllers => { :confirmations => 'confirmations', :omniauth_callbacks => 'users/omniauth_callbacks' }
end

app/models/device.rb
class Device < ActiveRecord::Base
  belongs_to :brand
  has_many :reviews
  is_impressionable :column_name => :impressions_count, :unique => :session_hash, :counter_cache => true
  acts_as_votable

  searchable do
	text :name
	text :brand_name do
		brand.name
	end
  end

  mount_uploader :thumbnail, ThumbnailUploader
  mount_uploader :thumbnailsm, ThumbnailsmUploader
  mount_uploaders :images, ImagesUploader
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
before_action :find_device, only: [:destroy]
before_filter :must_be_admin, only: [:edit, :new]
impressionist :actions=>[:show]
require 'will_paginate/array' 

def index
    if params[:search]
      @search = Device.search do
      fulltext params[:search]

      paginate :page => params[:page], :per_page => 40
    end
      @devices = @search.results
    else
    @devices = Device.all.paginate(:page => params[:page], :per_page => 40)
end
    set_meta_tags title: "Search results",
                keywords: "smartphones, mobile, specifications, reviews, camera, specs",
                description: "Home of device specifications and reviews"
end

def home
    @devices = Device.order('impressions_count DESC').first(12)
    set_meta_tags title: "Home of device specifications and reviews",
                keywords: "smartphones, mobile, specifications, reviews, camera, specs",
                description: "Home of device specifications and reviews"
end
 
def new
  @brand = Brand.find(params[:brand_id])
	  @device = Device.new
end

   def create
    @brand = Brand.find(params[:brand_id])
    @device = @brand.devices.create(device_params)
    @device.thumbnail = params[:fog]

    if @device.save
        redirect_to edit_brand_device_path(@brand, @device)
    else
        render 'new'
    end
   end


   def destroy
      @device.destroy
      redirect_to brand_path(@brand)
   end


def adminpanel
  @brands = Brand.all
end

def popular
   @devices = Device.order('impressions_count DESC').paginate(:page => params[:page], :per_page => 40)
end


def show
	@device = Device.find(params[:id])
  @popular = Device.order('impressions_count DESC').first(6)
  @reviews = @device.reviews.all
  if @reviews.present?
  @device.rating = @reviews.sum(:overall) / @reviews.size
  @speed_rating = ((@reviews.sum(:speed) / @reviews.size.to_f) / 5) * 100
  @durability_rating = ((@reviews.sum(:durability) / @reviews.size.to_f) / 5) * 100
  @display_rating = ((@reviews.sum(:display) / @reviews.size.to_f) / 5) * 100
  @camera_rating = ((@reviews.sum(:camera) / @reviews.size.to_f) / 5) * 100
  @price_quality_rating = ((@reviews.sum(:price_quality) / @reviews.size.to_f) / 5) * 100
  end
    @brand = @device.brand
    @brands = Brand.all.where.not(id: @device.brand.id)
    @brandsdevices = @brand.devices.all.where.not(id: @device.id)
    @images = @device.images << @device.thumbnail
    impressionist(@device, nil, :unique => [:session_hash])

    set_meta_tags title: "#{@device.brand.name} #{@device.name} - Device specifications and reviews",
                keywords: "#{@device.brand.name}, #{@device.name}, specs, specifications, reviews, ratings, dimensions, weight, CPU, processor, camera, GPU, Soc, speed, price, ram, battery, display, os",
                description: "#{@device.brand.name} #{@device.name} - Device specifications and reviews. #{@device.brand.name} #{@device.name} #{@device.year} is an #{@device.os} - based device with a #{@device.display} display and a #{@device.cpucores}-cored #{@device.cpu} CPU. It comes with #{@device.storage} of storage and weights #{@device.weight}."
end


def edit
    @device = Device.find(params[:id])
end

def update
    @device = Device.find(params[:id])
    if @device.update(device_params)
       redirect_to device_path(@device)
        else
        render 'new'
    end
end

def compare
    @device = Device.find(params[:device_id])
    @brand = @device.brand
    @device2 = Device.find(params[:dev])
    @brand2 = @device2.brand
    @images = @device.images << @device.thumbnail
    @images2 = @device2.images << @device2.thumbnail
  @reviews = @device.reviews.all
  if @reviews.present?
  @device.rating = ((@reviews.sum(:overall) / @reviews.size.to_f) / 5) * 100
  if @device.rating.nan?
    @device.rating = 0
  end
  @speed_rating = ((@reviews.sum(:speed) / @reviews.size.to_f) / 5) * 100
  @durability_rating = ((@reviews.sum(:durability) / @reviews.size.to_f) / 5) * 100
  @display_rating = ((@reviews.sum(:display) / @reviews.size.to_f) / 5) * 100
  @camera_rating = ((@reviews.sum(:camera) / @reviews.size.to_f) / 5) * 100
  @price_quality_rating = ((@reviews.sum(:price_quality) / @reviews.size.to_f) / 5) * 100
  end

  @reviews2 = @device2.reviews.all
  if @reviews2.present?
  @device2.rating = ((@reviews2.sum(:overall) / @reviews2.size.to_f) / 5) * 100
  if @device2.rating.nan?
    @device2.rating = 0
  end
  @speed_rating2 = ((@reviews2.sum(:speed) / @reviews2.size.to_f) / 5) * 100
  @durability_rating2 = ((@reviews2.sum(:durability) / @reviews2.size.to_f) / 5) * 100
  @display_rating2 = ((@reviews2.sum(:display) / @reviews2.size.to_f) / 5) * 100
  @camera_rating2 = ((@reviews2.sum(:camera) / @reviews2.size.to_f) / 5) * 100
  @price_quality_rating2 = ((@reviews2.sum(:price_quality) / @reviews2.size.to_f) / 5) * 100
  end
 set_meta_tags title: "#{@device.brand.name} #{@device.name} vs #{@device2.brand.name} #{@device2.name} - Devices comparison",
                keywords: "#{@device.brand.name}, #{@device.name}, specs, specifications, reviews, ratings, dimensions, weight, CPU, processor, camera, GPU, Soc, speed, price, ram, battery, display, os",
                description: "#{@device.brand.name} #{@device.name} - Specifications and reviews"
end

    private

        def device_params
            params.require(:device).permit(:name, :brand_id, :dimensions, :weight, :soc, :cpu, :cpucores, :gpu, :ram, :storage, :display, :battery, :os, :camera, :year, :thumbnail, :thumbnailsm, {images:[]})
        end

        def find_device
            @device = Device.find(params[:id])
        end

        def find_brand
        	@brand = Brand.find(params[:brand_id])
        end


        def must_be_admin
        unless current_user && current_user.admin?
          redirect_to root_path
        end
        end

end

app/helpers/device_helper.rb
module DeviceHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/adminpanel.html.erb
<div id="masterwrapper" class="row large-12 columns">
<div class="row" id="yieldwrapper">
<h1>Brands:</h1>
	<div id="indexwrapper" class="row large-12 columns float-left">
			<% @brands.each do |brand| %>
            <%= link_to brand_path(brand) do %>
			<%= image_tag(brand.brandav)%>
			<% end %>
			<% end %>
	</div>

<%= link_to "Add brand", new_brand_path %>
</div>
</div>

app/views/devices/edit.html.erb
<div id="masterwrapper" class="row large-12 columns">
   	<%= form_for @device do |device| %>
   <div class="formitem">
    <%= device.text_field :name, :class => "visibleclass itemname" %>
    <%= device.text_field :dimensions, :class => "visibleclass" %>
    <%= device.text_field :weight, :class => "visibleclass" %>
    <%= device.text_field :soc, :class => "visibleclass" %>
    <%= device.text_field :cpu, :class => "visibleclass" %>
    <%= device.text_field :cpucores, :class => "visibleclass" %>
    <%= device.text_field :gpu, :class => "visibleclass" %>
    <%= device.text_field :ram, :class => "visibleclass" %>
    <%= device.text_field :storage, :class => "visibleclass" %>
    <%= device.text_field :display, :class => "visibleclass" %>
    <%= device.text_field :battery, :class => "visibleclass" %>
    <%= device.text_field :os, :class => "visibleclass" %>
    <%= device.text_field :camera, :class => "visibleclass" %>
    <%= device.number_field :year, :class => "visibleclass" %>
    <%= device.file_field :thumbnailsm, :class => "thumbnail_sm" %> 
    <%= device.file_field :thumbnail %> 
    <%= device.file_field :images, multiple: true %> 
    <%= device.submit %>
   </div>
    <% end %>
<%= link_to 'Destroy',  @device,  method: :delete, data: { confirm: 'Are you sure?' } %>
    <script type="text/javascript">
        $('input.itemname').click(function() {
    $('input[type="text"]').toggleClass('visibleclass');
});
    </script>
</div>

app/views/devices/home.html.erb
<div id="homepage" class="row large-12 columns">

<div id="logohomewrap">
</div>
<h1 class="mb hide-for-medium">Popular devices:</h1>
</div>

<div id="home-popular" style="padding-top: 200px;">
	<div id="indexwrapper" class="row large-12 small-12 columns">
	<% @devices.each do |device| %>

	    <%= link_to device_path(device) do %>
	    <div class="indexitemwrap row large-2 small-4 columns float-left">
		    <div class="indexitem">
		    	<div class="indexthumbnail">
		    	<% if device.thumbnailsm.present? %>
		    	<%= image_tag(device.thumbnailsm) %>
		    	<% else %>
		    	<%= image_tag('nophoto.png') %>
		    	<% end %>
		    	</div>
		    	<div class="indexname">
			    	<div class="indexbrandname"><%= device.brand.name %></div>
			    	<div class="indexdevicename"><p><b><%= device.name %></b></p></div>
		    	</div>
		<div class="item-tooltip" style="margin-left: 140px;">
			<span class="index-rating">
			<% device.rating.round.times do %>
			<%= image_tag('radiostarfilled.png') %>
			<% end %>
			</span>
			<ul>
				<li><b>Dimensions:</b> <%= device.dimensions %></li>
				<li><b>CPU:</b> <%= device.cpu %></li>
				<li><b>RAM:</b> <%= device.ram %></li>
				<li><b>Display:</b> <%= device.display %></li>
				<li><b>Camera:</b> <%= device.camera %></li>
			</ul>
		</div>
		    </div>

	    </div>
	    <% end %>


	<% end %>
	</div>

</div>

app/views/devices/index.html.erb
<div id="masterwrapper" class="row large-12 columns">
<div class="row" id="yieldwrapper">
<div class="row large-8 small-12 columns float-left">
<h2>Search results:</h2>
</div>

	<div id="indexwrapper" class="row large-8 small-12 columns float-left">
	<% @devices.each do |device| %>

	    <%= link_to device_path(device) do %>
	    <div class="indexitemwrap row large-2 small-4 columns float-left">
		    <div class="indexitem">
		    	<div class="indexthumbnail">
		    	<% if device.thumbnailsm.present? %>
		    	<%= image_tag(device.thumbnailsm) %>
		    	<% else %>
		    	<%= image_tag('nophoto.png') %>
		    	<% end %>
		    	</div>
		    	<div class="indexname">
			    	<div class="indexbrandname"><%= device.brand.name %></div>
			    	<div class="indexdevicename"><p><b><%= device.name %></b></p></div>
		    	</div>
		<div class="item-tooltip">
			<span class="index-rating">
			<% device.rating.round.times do %>
			<%= image_tag('radiostarfilled.png') %>
			<% end %>
			</span>
			<ul>
				<li><b>Dimensions:</b> <%= device.dimensions %></li>
				<li><b>CPU:</b> <%= device.cpu %></li>
				<li><b>RAM:</b> <%= device.ram %></li>
				<li><b>Display:</b> <%= device.display %></li>
				<li><b>Camera:</b> <%= device.camera %></li>
			</ul>
		</div>
		    </div>
	    </div>
	    <% end %>


	<% end %>
	<div class="row large-12 columns float-left"><%= will_paginate %></div>
	</div>

</div>
</div>

app/views/devices/new.html.erb
<div id="masterwrapper" class="row large-12 columns">
   	<%= form_for @brand do |f| %>
   <div class="formitem">
   <%= f.fields_for :devices, [Device.new] do |device| %>
            <%= device.label :name %>
            <%= device.text_field :name, :class => "visibleclass name" %>
            <%= device.label :dimensions %>
            <%= device.text_field :dimensions, :class => "visibleclass" %>
            <%= device.label :weight %>
            <%= device.text_field :weight, :class => "visibleclass" %>
            <%= device.label :soc %>
            <%= device.text_field :soc, :class => "visibleclass" %>
            <%= device.label :cpu %>
            <%= device.text_field :cpu, :class => "visibleclass" %>
            <%= device.label :cpucores %>
            <%= device.text_field :cpucores, :class => "visibleclass" %>
            <%= device.label :gpu %>
            <%= device.text_field :gpu, :class => "visibleclass" %>
            <%= device.label :ram %>
            <%= device.text_field :ram, :class => "visibleclass" %>
            <%= device.label :storage %>
            <%= device.text_field :storage, :class => "visibleclass" %>
            <%= device.label :display %>
            <%= device.text_field :display, :class => "visibleclass" %>
            <%= device.label :battery %>
            <%= device.text_field :battery, :class => "visibleclass" %>
            <%= device.label :os %>
            <%= device.text_field :os, :class => "visibleclass" %>
            <%= device.label :camera %>
            <%= device.text_field :camera, :class => "visibleclass" %>
            <%= device.label :year %>
            <%= device.number_field :year, :class => "visibleclass" %>
            <%= device.label :thumbnail %>
    <%= device.file_field :thumbnailsm, :class => "thumbnail_sm" %>
    <%= device.label "main image" %>
    <%= device.file_field :thumbnail %>
    <%= device.label :images %>
    <%= device.file_field :images, multiple: true %> 
    <%= device.submit %>
   </div>
    <% end %>
    <% end %>
</div>

app/views/devices/popular.html.erb
<div id="masterwrapper" class="row large-12 columns">
<div class="row" id="yieldwrapper">
<div class="row large-8 small-12 columns float-left">
<h2>Popular devices:</h2>
</div>

	<div id="indexwrapper" class="row large-12 small-12 columns float-left">
	<% @devices.each do |device| %>

	    <%= link_to device_path(device) do %>
	    <div class="indexitemwrap row large-2 small-4 columns float-left">
		    <div class="indexitem">
		    	<div class="indexthumbnail">
		    	<% if device.thumbnailsm.present? %>
		    	<%= image_tag(device.thumbnailsm) %>
		    	<% else %>
		    	<%= image_tag('nophoto.png') %>
		    	<% end %>
		    	</div>
		    	<div class="indexname">
			    	<div class="indexbrandname"><%= device.brand.name %></div>
			    	<div class="indexdevicename"><p><b><%= device.name %></b></p></div>
		    	</div>
		<div class="item-tooltip">
			<span class="index-rating">
			<% device.rating.round.times do %>
			<%= image_tag('radiostarfilled.png') %>
			<% end %>
			</span>
			<ul>
				<li><b>Dimensions:</b> <%= device.dimensions %></li>
				<li><b>CPU:</b> <%= device.cpu %></li>
				<li><b>RAM:</b> <%= device.ram %></li>
				<li><b>Display:</b> <%= device.display %></li>
				<li><b>Camera:</b> <%= device.camera %></li>
			</ul>
		</div>
		    </div>
	    </div>
	    <% end %>


	<% end %>
	<div class="row large-12 columns float-left"><%= will_paginate %></div>
	</div>

</div>
</div>