config/routes.rb
Rails.application.routes.draw do

  resources :articles
root 'devices#home'

resources :brands do
get '/correct', to: 'brands#correct'
get '/count', to: 'brands#count_scrapes'
resources :devices
end

resources :devices do
resources :reviews
get '/compare', to: 'devices#compare'
end

get '/adminpanel', to: 'devices#adminpanel'

get '/popular', to: 'devices#popular'

devise_for :users, :controllers => { :confirmations => 'confirmations', :omniauth_callbacks => 'users/omniauth_callbacks' }
end

app/models/brand.rb
class Brand < ActiveRecord::Base
has_many :devices, dependent: :destroy
acts_as_votable


mount_uploader :brandav, BrandavUploader
accepts_nested_attributes_for :devices

end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
before_action :find_brand, only: [:destroy]
before_filter :must_be_admin, only: [:edit, :new]
def index
	@brands = Brand.all
    @popular = Device.order('impressions_count DESC').first(6)
end

def home
    @brands = Brand.all
end

def new
	@brand = Brand.new
end

def create
    @brand = Brand.new(brand_params)
    if @brand.save
    	redirect_to edit_brand_path(@brand)
    else
    	render 'new'
    end
end


def show
    @brand = Brand.find(params[:id])
    @popular = Device.order('impressions_count DESC').first(6)
    @brands = Brand.all.where.not(id: @brand.id)
    @devices = @brand.devices.all
    set_meta_tags title: "#{@brand.name} devices - Home of device specifications and reviews",
                keywords: "smartphones, mobile, specifications, reviews, camera",
                description: "Home of device specifications and reviews"
end

def correct
    @brand = Brand.find(params[:brand_id])
    @devices = @brand.devices.all
end

def destroy
	@brand.destroy
    redirect_to root_path
end

def edit
    @brand = Brand.find(params[:id])
    @devices = @brand.devices.all 
end

def update
    @brand = Brand.find(params[:id])
    if @brand.update(brand_params)
       redirect_to edit_brand_path(@brand)
        else
        render 'new'
    end
end

    private

        def find_brand
            @brand = Brand.find(params[:id])
        end

        def brand_params
            params.require(:brand).permit(:name, :brandav, devices_attributes: [:id, :name, :dimensions, :weight, :soc, :cpu, :cpucores, :gpu, :ram, :storage, :display, :battery, :os, :camera, :year, :thumbnail, :thumbnailsm, {images:[]}])
        end

        def device_params
            params.require(:device).permit(:name, :brand_id, :dimensions, :weight, :soc, :cpu, :cpucores, :gpu, :ram, :storage, :display, :battery, :os, :camera, :year, :thumbnail, :thumbnailsm, {images:[]})
        end

        def must_be_admin
        unless current_user && current_user.admin?
          redirect_to root_path
        end
        end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/views/brands/_formitem.html.erb
    <%= f.fields_for :devices, [Device.new] do |device| %>
   <div class="formitem">
    <%= device.text_field :name %>
    <%= device.text_field :dimensions %>
    <%= device.text_field :weight %>
    <%= device.text_field :soc %>
    <%= device.text_field :cpu %>
    <%= device.text_field :cpucores %>
    <%= device.text_field :gpu %>
    <%= device.text_field :ram %>
    <%= device.text_field :storage %>
    <%= device.text_field :display %>
    <%= device.text_field :battery %>
    <%= device.text_field :os %>
    <%= device.text_field :camera %>
    <%= device.number_field :year %>
    <%= device.file_field :thumbnailsm, :class => "thumbnail_sm" %> 
    <%= device.file_field :thumbnail %> 
    <%= device.file_field :images, multiple: true %> 
   </div>
    <% end %>

app/views/brands/correct.html.erb
<%= form_for @brand do |f| %>
		
		<%= f.fields_for :devices do |device| %>
		<div class="formitem">
		    <%= device.text_field :id, :placeholder => "device.id", :class => "visibleclass id" %>
		    <%= device.text_field :name, :class => "visibleclass name" %>
		    <%= device.text_field :dimensions, :class => "visibleclass" %>
		    <%= device.text_field :weight, :class => "visibleclass" %>
		    <%= device.text_field :soc, :class => "visibleclass" %>
		    <%= device.text_field :cpu, :class => "visibleclass" %>
		    <%= device.text_field :cpucores, :class => "visibleclass" %>
		    <%= device.text_field :gpu, :class => "visibleclass" %>
		    <%= device.text_field :ram, :class => "visibleclass" %>
		    <%= device.text_field :storage, :class => "visibleclass" %>
		    <%= device.text_field :display, :class => "visibleclass" %>
		    <%= device.text_field :battery, :class => "visibleclass" %>
		    <%= device.text_field :os, :class => "visibleclass" %>
		    <%= device.text_field :camera, :class => "visibleclass" %>
		    <%= device.number_field :year, :class => "visibleclass" %>
		</div>
		<% end %>
<% end %>

app/views/brands/edit.html.erb
<div id="masterwrapper" class="row large-12 columns">

<%= form_for @brand do |f| %>
		<%= f.fields_for :devices do |device| %>
		<div class="formitem">
		    <%= device.label :id %>
		    <%= device.text_field :id, :placeholder => "device.id", :class => "visibleclass id" %>
		    <%= device.label :name %>
		    <%= device.text_field :name, :class => "visibleclass name" %>
		    <%= device.label :dimensions %>
		    <%= device.text_field :dimensions, :class => "visibleclass" %>
		    <%= device.label :weight %>
		    <%= device.text_field :weight, :class => "visibleclass" %>
		    <%= device.label :soc %>
		    <%= device.text_field :soc, :class => "visibleclass" %>
		    <%= device.label :cpu %>
		    <%= device.text_field :cpu, :class => "visibleclass" %>
		    <%= device.label :cpucores %>
		    <%= device.text_field :cpucores, :class => "visibleclass" %>
		    <%= device.label :gpu %>
		    <%= device.text_field :gpu, :class => "visibleclass" %>
		    <%= device.label :ram %>
		    <%= device.text_field :ram, :class => "visibleclass" %>
		    <%= device.label :storage %>
		    <%= device.text_field :storage, :class => "visibleclass" %>
		    <%= device.label :display %>
		    <%= device.text_field :display, :class => "visibleclass" %>
		    <%= device.label :battery %>
		    <%= device.text_field :battery, :class => "visibleclass" %>
		    <%= device.label :os %>
		    <%= device.text_field :os, :class => "visibleclass" %>
		    <%= device.label :camera %>
		    <%= device.text_field :camera, :class => "visibleclass" %>
		    <%= device.label :year %>
		    <%= device.number_field :year, :class => "visibleclass" %>
		</div>
		<% end %>
<% end %>


</div>

app/views/brands/index.html.erb
<div id="masterwrapper" class="row large-12 columns">
<div class="row" id="yieldwrapper">
<h2>Choose brand:</h2>
	<div id="indexwrapper" class="row large-12 small-12 columns float-left">

			<% @brands.each do |brand| %>
			<div class="brand-indexitem large-2 columns float-left">
            <%= link_to brand_path(brand) do %>
			<%= image_tag(brand.brandav)%>
			<% end %>
			</div>
			<% end %>
	</div>



</div>
</div>

app/views/brands/new.html.erb
<div id="masterwrapper" class="row large-12 columns">

<%= form_for @brand do |f| %>
  <%= f.label :name %>:
  <%= f.text_field :name %><br />
  <%= f.file_field :brandav %>

  <%= f.submit %>
<% end %>
</div>

app/views/brands/show.html.erb
<div id="masterwrapper" class="row large-12 columns">
<% if user_signed_in? %>
<% if current_user.admin? %>
<div class="row large-12 columns">
	<%= link_to "Add Device", new_brand_device_path(@brand) %>
</div>
<% end %>
<% end %>
<div id="branddevices" class="row large-12 columns">
        <div id="brandpicwrap" class="row large-1 small-2 columns float-left">
			<%= link_to brand_path(@brand) do %>
			<%= image_tag(@brand.brandav, :class => "brandpic")%>
			<% end %>
		</div>
		<div id="brandslist" class="row large-11 small-10 columns float-left">
			<% @brands.each do |brand| %>
            <%= link_to brand_path(brand) do %>
			<%= image_tag(brand.brandav)%>
			<% end %>
			<% end %>
		</div>
</div>

<div class="row" id="yieldwrapper">
<div class="row large-8 small-12 columns float-left">
	<h2><%= @brand.name %> devices:</h2>
</div>
<div id="indexwrapper" class="row large-8 small-12 columns float-left">
<% @devices.each do |device| %>

    <%= link_to device_path(device) do %>
    <div class="indexitemwrap row large-2 small-4 columns float-left">
	    <div class="indexitem">
	    	<div class="indexthumbnail">
		    	<% if device.thumbnailsm.present? %>
		    	<%= image_tag(device.thumbnailsm) %>
		    	<% else %>
		    	<%= image_tag('nophoto.png') %>
		    	<% end %>
	    	<%= image_tag(device.thumbnailsm) %>
	    	</div>
	    	<div class="indexname">
		    	<div class="indexbrandname"><%= device.brand.name %></div>
		    	<div class="indexdevicename"><p><b><%= device.name %></b></p></div>
	    	</div>
		<div class="item-tooltip">
			<span class="index-rating">
			<% device.rating.round.times do %>
			<%= image_tag('radiostarfilled.png') %>
			<% end %>
			</span>
			<ul>
				<li><b>Dimensions:</b> <%= device.dimensions %></li>
				<li><b>CPU:</b> <%= device.cpu %></li>
				<li><b>RAM:</b> <%= device.ram %></li>
				<li><b>Display:</b> <%= device.display %></li>
				<li><b>Camera:</b> <%= device.camera %></li>
			</ul>
		</div>
	    </div>
    </div>
    <% end %>


<% end %>
</div>
<div id="rightwrap" class="row large-4 columns float-right">
	<div id="popularwrap" class="row large-12 columns" data="<%= @brand.id %>">
	<h4 id="popular-title">Popular devices</h4>
	<% @popular.each do |device| %>
	    <%= link_to device_path(device) do %>
    <div class="indexitemwrap row large-4 small-4 columns float-left">
	    <div class="indexitem">
	    	<div class="indexthumbnail">
		    	<% if device.thumbnailsm.present? %>
		    	<%= image_tag(device.thumbnailsm) %>
		    	<% else %>
		    	<%= image_tag('nophoto.png') %>
		    	<% end %>
	    	<%= image_tag(device.thumbnailsm) %>
	    	</div>
	    	<div class="indexname">
		    	<div class="indexbrandname"><%= device.brand.name %></div>
		    	<div class="indexdevicename"><p><b><%= device.name %></b></p></div>
	    	</div>
		<div class="item-tooltip">
			<span class="index-rating">
			<% device.rating.round.times do %>
			<%= image_tag('radiostarfilled.png') %>
			<% end %>
			</span>
			<ul>
				<li><b>Dimensions:</b> <%= device.dimensions %></li>
				<li><b>CPU:</b> <%= device.cpu %></li>
				<li><b>RAM:</b> <%= device.ram %></li>
				<li><b>Display:</b> <%= device.display %></li>
				<li><b>Camera:</b> <%= device.camera %></li>
			</ul>
		</div>
	    </div>
    </div>
	    <% end %>
	<% end %>
	</div>
</div>
</div>
</div>