config/routes.rb
Rails.application.routes.draw do

  resources :articles
root 'devices#home'

resources :brands do
get '/correct', to: 'brands#correct'
get '/count', to: 'brands#count_scrapes'
resources :devices
end

resources :devices do
resources :reviews
get '/compare', to: 'devices#compare'
end

get '/adminpanel', to: 'devices#adminpanel'

get '/popular', to: 'devices#popular'

devise_for :users, :controllers => { :confirmations => 'confirmations', :omniauth_callbacks => 'users/omniauth_callbacks' }
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= favicon_link_tag 'favicon.ico' %>
    <%= display_meta_tags(default_meta_tags) %>

    <%= stylesheet_link_tag    "application" %>
    <%= stylesheet_link_tag    "custom" %>
    <%= stylesheet_link_tag    "swipebox" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "jquery.swipebox", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

            <div id="topbar">
               <div class="row">
                    <div class="row large-3 small-2 columns float-left">
                    <span id="logo" class="float-left"><%= link_to "Home", root_path %></span>
                    <span class="navbar-link float-left show-for-medium"><%= link_to "Brands", brands_path %></span>
                    <span class="navbar-link float-left show-for-medium"><%= link_to "Top devices", '/popular' %></span>
                    </div>
                    <div class="row large-5 small-5 columns float-left">
                    <% if user_signed_in? %>
                    
                      <button id="signoutbtn" class="float-right"><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></button>
                      <% if current_user.admin? %>
                      <button id="admin-panel" class="float-right"><%= link_to "Admin panel", '/adminpanel' %></button> 
                      <% end %>                
                    <% else %>
                      <div class="float-right hide-for-medium">
                      <button id="search-mb-button" type="button">
                      <%= image_tag("searchbtn-mb.png") %>
                      </button>
                      </div>
                        <button id="signupbtn" class="float-right"><%= link_to "Sign Up", new_user_registration_path %></button>
                        <button id="loginbtn" class="float-right"><%= link_to "Log In", new_user_session_path %></button>
                      
                      <% end %>

                    </div>
                          <div class="row small-12 columns float-left hide-for-medium" id="search-dropdown">
                          <%= form_for devices_path, :method => :get, :url => url_for(:controller => '/devices', :action => 'index'), :html => {:id => "searchform", :class => "input-group"} do %>
                              <%= text_field_tag :search, params[:search], :class => "input-group-field" %>
                              <div class="input-group-button">
                              <%= submit_tag "Search", :name => nil %>
                              </div>
                          <% end %>
                          </div>
                          <script type="text/javascript">
                            $('#search-mb-button').click(function(){
                              $('#search-dropdown').toggle('display');
                            })
                          </script>
                    <div class="row large-4 columns float-right show-for-medium">
                    <%= form_for devices_path, :method => :get, :url => url_for(:controller => '/devices', :action => 'index'), :html => {:id => "searchform", :class => "input-group"} do %>
                        <%= text_field_tag :search, params[:search], :class => "input-group-field" %>
                        <div class="input-group-button">
                        <%= submit_tag "Search", :name => nil %>
                        </div>
                    <% end %>
                    </div>

               </div>
            </div>

    <%= yield %>

        <div id="bottom-bar" class="expanded row large-12 columns float-center">
<p class="disclaimer">The information on this website is provided on "as is, as available basis" without warranty of any kind. We are not responsible for any omissions, inaccuracies or other errors in the information it publishes. All warranties with respect to this information are disclaimed. Reproduction of any part of this website in its entirety or partially or in any form or medium without prior written permission is prohibited. The trademarks, marques and logos of the manufacturers of devices, software, hardware, etc. are the property of their respective owners. <b>Contact us:</b>
</p>
<div id="cookies-disclaimer">
We use cookies to personalise content and ads, to provide social media features and to analyse our traffic. We also share information about your use of our site with our social media, advertising and analytics partners who may combine it with other information you’ve provided to them or they’ve collected from your use of their services. 
</div>
        </div>
        <p class="notice alert devise-message"><%= notice %><%= alert %></p>

  </body>
</html>